# Generated by Django 4.0.3 on 2022-04-18 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_favorite_recipe_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Количество ингредиента'),
            preserve_default=False,
        ),
    ]
